[package]
name = "webex"
version = "0.1.1"
authors = ["Scott Hutton <shutton@pobox.com>"]
edition = "2018"
description = "Interface to Webex Teams REST and WebSocket APIs"
keywords = ["webex", "spark"]
categories = ["asynchronous"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shutton/webex-rust.git"

[dependencies]
async-std = "1.4.0"
futures = "0.3.1"
futures-util = "0.3.1"
hyper = "0.13"
hyper-tls = "0.4.1"
log = "0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2.1", features = ["time", "stream", "fs", "macros", "uds", "io-util"] }
tokio-tls = "0.3.0"
tokio-tungstenite = { version = "0.10.1", features = ["tls"] }
tungstenite = "0.10.1"
url = "2.1.1"
uuid = { version = "0.8", features = ["v4"] }
